### ISSUE TITLE
Behaviour differs from what described on sample page.

### ISSUE THREAD

**Issue by SlausB** [tomsmeding/circular-buffer#3]
`var cb = new CircularBuffer( 5 );
cb.enq( 1 );
cb.enq( 2 );
cb.enq( 3 );
cb.enq( 4 );
cb.enq( 5 );
while ( cb.size() > 0 )
{
    console.log( cb.deq() );
}`

prints
1
2
3
4
5

but sample page stands that it will be printed on reversed order (4, 3, 2, 1).
Did I understood it wrong?

**Comment by lieuwex** [comment]
This seems to be an error in the documentation @tomsmeding

**Comment by tomsmeding** [comment]
Thanks for the report! @lieuwex: fully correct. I just fixed the docs and added the docs example to the test suite. Committing right now...
